version: 0.2
env:
  variables:
    DATABASE_URL: ""
phases:
  build:
    commands:
      - echo "------> ${DATABASE_URL}"
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
